server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/order/**
          #          - CheckAuth=chad
          filters:
    #            - CheckAuth=chad
    #          - StripPrefix=1

    nacos:
      discovery:
        server-addr: 47.94.83.242:8848
        username: nacos
        password: nacos
