server:
  port: 8031
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 47.94.83.242:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
